<?php
/**
 * @file
 * Code for the Sample Asset free HTML.
 */

/**
 * Implements hook_default_asset_type().
 */
function asset_freehtml_default_asset_type() {
  $items = array();
  $items['free_html'] = entity_import('asset_type', '{
    "type" : "free_html",
    "name" : "Free HTML",
    "icon" : "AddFreeHTML.png",
    "description" : "",
    "help" : "",
    "weight" : "4",
    "locked" : "0"
  }');
  return $items;
}
