<?php
    define('DRUPALSIB_SITE_THEME_PATH', drupal_get_path('theme', 'drupalsib'));

    function drupalsib_site_init(){
//      kpr(views_get_view_result('dossier', 'panel_pane_1')); die();
    }
    
    function drupalsib_site_ctools_plugin_directory($module, $plugin){
      if ($module == 'ctools' || $module == 'page_manager' || ($module == 'panels' && in_array($plugin, array('layouts')))) {
        return 'plugins/' . $plugin;
      }
    }