<?php
/**
 * @file
 * Emvideo vimeo module.
 */

/**
 * Implements hook_emvideo_parse().
 */
function emvideo_vimeo_emvideo_parse($url) {
  $matches = array();

  if (preg_match('/vimeo\.com\/([0-9]+)/', $url, $matches)) {
    $videoid = $matches[1];

    $ret = array(
      'source' => "http://www.vimeo.com/moogaloop.swf?clip_id=$videoid",
      'provider' => 'vimeo',
    );

    try {
      $xml = simplexml_load_file("http://vimeo.com/api/v2/video/$videoid.xml");
      if ($xml) {
        $xml = $xml->video;
        $ret['snapshot'] = $xml->thumbnail_medium;
      }
    }
    catch (Exception $ex) {
      watchdog('emvideo_vimeo', $ex->getMessage());
    }

    return $ret;
  }

  return FALSE;
}
